apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: ai-saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://0.0.0.0:8001"
        - name: DATABASE_URI
          value: "mongo://mongodb:27017"
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "8001"]
