apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: ai-saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo
        image: yolo-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: TRACKING_URI
          value: "http://mlflow:8001"
        - name: DATABASE_URI
          value: "mongodb://mongodb:27017"
